apiVersion: apps/v1
kind: Deployment
metadata:
  name: connector
  namespace: inspire-validator
  labels:
    app: connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connector
  template:
    metadata:
      name: connector
      labels:
        app: connector
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: connector
          image: ghcr.io/mihai-negru/kafka-inspire-validator-connector:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: connector-secret
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: KAFKA_VALIDATOR_GROUP_ID
              valueFrom:
                secretKeyRef:
                  name: connector-secret
                  key: KAFKA_VALIDATOR_GROUP_ID
            - name: KAFKA_VALIDATOR_INPUT_TOPIC
              valueFrom:
                secretKeyRef:
                  name: connector-secret
                  key: KAFKA_VALIDATOR_INPUT_TOPIC
            - name: KAFKA_VALIDATOR_OUTPUT_TOPIC
              valueFrom:
                secretKeyRef:
                  name: connector-secret
                  key: KAFKA_VALIDATOR_OUTPUT_TOPIC
            - name: VALIDATOR_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: connector-secret
                  key: VALIDATOR_BASE_URL
            - name: VALIDATOR_ETS_IDS_ADMINISTRATIVE_UNITS
              valueFrom:
                secretKeyRef:
                  name: connector-secret
                  key: VALIDATOR_ETS_IDS_ADMINISTRATIVE_UNITS
            - name: VALIDATOR_ETS_IDS_GEOGRAPHICAL_NAMES
              valueFrom:
                secretKeyRef:
                  name: connector-secret
                  key: VALIDATOR_ETS_IDS_GEOGRAPHICAL_NAMES
            - name: VALIDATOR_POLL_DELAY
              valueFrom:
                secretKeyRef:
                  name: connector-secret
                  key: VALIDATOR_POLL_DELAY
            - name: EXECUTOR_CORE_POOL_SIZE
              valueFrom:
                secretKeyRef:
                  name: connector-secret
                  key: EXECUTOR_CORE_POOL_SIZE
            - name: EXECUTOR_MAX_POOL_SIZE
              valueFrom:
                secretKeyRef:
                  name: connector-secret
                  key: EXECUTOR_MAX_POOL_SIZE
            - name: EXECUTOR_QUEUE_CAPACITY
              valueFrom:
                secretKeyRef:
                  name: connector-secret
                  key: EXECUTOR_QUEUE_CAPACITY
            - name: EXECUTOR_THREAD_NAME_PREFIX
              valueFrom:
                secretKeyRef:
                  name: connector-secret
                  key: EXECUTOR_THREAD_NAME_PREFIX
            - name: BRIDGE_LOG_ROOT_LEVEL
              valueFrom:
                secretKeyRef:
                  name: connector-secret
                  key: BRIDGE_LOG_ROOT_LEVEL
            - name: BRIDGE_LOG_FILE
              valueFrom:
                secretKeyRef:
                  name: connector-secret
                  key: BRIDGE_LOG_FILE