apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: inspire-validator
resources:
  - deployment.yaml
  - service.yaml
  - validator-etf-pvc.yaml
  - validator-deployment.yaml
  - validator-service.yaml
secretGenerator:
  - name: connector-secret
    envs:
      - .env
    type: Opaque
generatorOptions:
  disableNameSuffixHash: true