apiVersion: v1
kind: Service
metadata:
  name: connector
  namespace: inspire-validator
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
spec:
  selector:
    app: connector
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP