apiVersion: v1
kind: Service
metadata:
  name: validator
  namespace: inspire-validator
  labels:
    app: validator
spec:
  selector:
    app: validator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP