apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink-inspire-application
  namespace: flink
spec:
  image: matrix22/flink-inspire:latest
  flinkVersion: v1_20
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  job:
    jarURI: local:///opt/flink/usrlib/flink-inspire-transformer.jar
    parallelism: 2
    upgradeMode: stateless
