apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flink
resources:
  - flink-configuration-configmap.yaml.yaml
  - jobmanager-service.yaml
  - jobmanager-session-deployment-non-ha.yaml
  - taskmanager-session-deployment.yaml
generatorOptions:
  disableNameSuffixHash: true