#!/usr/bin/env bash

sudo brew services start socket_vmnet

minikube config set cpus 10
minikube config set memory 16384
minikube config set disk-size 100g

minikube start --driver=qemu --network=socket_vmnet --cni=calico
sudo minikube tunnel > /dev/null 2>&1 < /dev/null &