#!/usr/bin/env bash

set -e

ARGOCD_PASS="admin123"
REPO_URL="https://github.com/mihai-negru/BachelorDegree"

kubectl apply -f argocd/namespaces.yaml --server-side

#kubectl apply -f manifests/monitoring/prometheus-stack/secret.yaml
#helm upgrade --install kube-prometheus-stack prometheus-community/kube-prometheus-stack                 \
#    --namespace=monitoring                                                                              \
#    --values manifests/monitoring/prometheus-stack/values.yaml > /dev/null 2>&1

for namespace in $(kubectl get namespaces -o jsonpath='{range .items[*]}{.metadata.name}{" "}'); do
    kubectl create secret docker-registry ghcr-secret                                                   \
        --namespace="$namespace"                                                                        \
        --docker-server=ghcr.io                                                                         \
        --docker-username="$GITHUB_REGISTRY_USERNAME" --docker-password="$GITHUB_REGISTRY_PASSWORD"     \
        --docker-email="$GITHUB_REGISTRY_EMAIL"                                                         \
        --dry-run=client -o yaml | kubectl apply -f -
done

kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
kubectl patch secret -n argocd argocd-secret -p '{"stringData": { "admin.password": "'"$(htpasswd -bnBC 10 "" $ARGOCD_PASS | tr -d ':\n')"'"}}'
kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'
kubectl patch configmap argocd-cm -n argocd --type merge -p '{ "data": { "kustomize.buildOptions": "--enable-helm --load-restrictor LoadRestrictionsNone" }}'
kubectl rollout restart deployment argocd-server -n argocd

argocd_load_ip=$(kubectl get svc -n argocd argocd-server -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
while [[ -z "$argocd_load_ip" ]] || [[ "$argocd_load_ip" == "pending" ]]; do
    echo "Waiting for argocd load balancer IP..."
    sleep 2
    argocd_load_ip=$(kubectl get svc -n argocd argocd-server -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
done

echo "ArgoCD LoadBalancer IP: $argocd_load_ip"
argocd login "$argocd_load_ip" --username admin --password "$ARGOCD_PASS" --skip-test-tls --insecure > /dev/null 2>&1 || 1
argocd repo add "$REPO_URL" --username "dummy" --password "$GITHUB_REGISTRY_PASSWORD" --name k8s

echo "Updating /etc/hosts to add argocd"
sudo sed -i '' "/[[:space:]]argocd.local/d" /etc/hosts
echo "$argocd_load_ip    argocd.local" | sudo tee -a /etc/hosts > /dev/null
echo "You can now access argocd at: http://argocd.local"

kubectl apply -f argocd/apps.yaml