apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cassandra

configMapGenerator:
  - name: cassandra-init-cql
    files:
      - init.cql
helmCharts:
  - name: cassandra
    releaseName: cassandra
    version: 12.3.7
    repo: https://charts.bitnami.com/bitnami
    valuesFile: values.yaml
generatorOptions:
  disableNameSuffixHash: true