apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka
helmCharts:
  - name: kafka
    releaseName: kafka
    version: 32.2.4
    repo: https://charts.bitnami.com/bitnami
    valuesFile: values.yaml
generatorOptions:
  disableNameSuffixHash: true