replicaCount: 1

dbUser:
  existingSecret:
    cassandra-secret
initDBConfigMap: cassandra-init-cql

image:
  debug: true

cluster:
  seedCount: 1

jvm:
  maxHeapSize: 1G
  newHeapSize: 200M

resources:
  limits:
    cpu: 4
    memory: 8Gi
  requests:
    cpu: 2
    memory: 4Gi