replicaCount: 3

initDBConfigMap: cassandra-init-cql

livenessProbe:
  enabled: true
  initialDelaySeconds: 180
  periodSeconds: 60
  timeoutSeconds: 60

readinessProbe:
  enabled: true
  initialDelaySeconds: 180
  periodSeconds: 60
  timeoutSeconds: 60

startupProbe:
  enabled: true
  initialDelaySeconds: 180
  periodSeconds: 60
  timeoutSeconds: 60

image:
  debug: true

cluster:
  seedCount: 3