replicaCount: 3

initDBConfigMap: cassandra-init-cql

livenessProbe:
  enabled: true
  initialDelaySeconds: 180
  periodSeconds: 60
  timeoutSeconds: 60

readinessProbe:
  enabled: true
  initialDelaySeconds: 180
  periodSeconds: 60
  timeoutSeconds: 60

startupProbe:
  enabled: false
  initialDelaySeconds: 180
  periodSeconds: 60
  timeoutSeconds: 60

image:
  debug: true

cluster:
  seedCount: 3

jvm:
  maxHeapSize: 1G
  newHeapSize: 800M

resources:
  limits:
    cpu: 8
    memory: 8Gi
  requests:
    cpu: 4
    memory: 8Gi