replicaCount: 1

persistence:
  enabled: false

initDBConfigMap: cassandra-init-cql

readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 30
  failureThreshold: 10

startupProbe:
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 30
  failureThreshold: 10