replicaCount: 1

initDBConfigMap: cassandra-init-cql

livenessProbe:
  enabled: true
  initialDelaySeconds: 15
  periodSeconds: 30
  timeoutSeconds: 30
  failureThreshold: 10

readinessProbe:
  enabled: true
  initialDelaySeconds: 15
  periodSeconds: 30
  timeoutSeconds: 30
  failureThreshold: 10

startupProbe:
  enabled: true
  initialDelaySeconds: 15
  periodSeconds: 30
  timeoutSeconds: 30
  failureThreshold: 10

image:
  debug: true

cluster:
  seedCount: 1

jvm:
  maxHeapSize: 2G
  newHeapSize: 800M

resources:
  limits:
    cpu: 8
    memory: 8Gi
  requests:
    cpu: 4
    memory: 8Gi