name: Build Kafka Inspire Validator Connector

on:
  push:
    branches:
      - master
    paths:
      - kafka-inspire-validator-connector/pom.xml
      - kafka-inspire-validator-connector/src/main/**
      - kafka-inspire-validator-connector/Dockerfile
      - .github/workflows/build-kafka-inspire-validator-connector.yml

env:
  REGISTRY: ghcr.io
  SERVICE: ${{ github.repository_owner }}/kafka-inspire-validator-connector
  TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./kafka-inspire-validator-connector
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.SERVICE }}:${{ env.TAG }}
          platforms: linux/arm64